# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LocalSoftware
                                 A QGIS plugin
 Connecting CAD and GIS software
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-10-12
        git sha              : $Format:%H$
        copyright            : (C) 2021 by LocalSoftware
        email                : csandova@mit.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject, QgsMessageLog
from qgis.core import QgsVectorLayer, QgsProject, QgsJsonUtils



# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .local_software_dialog import LocalSoftwareDialog
import os.path
import json

# Import Firebase libraries
import firebase_admin
from firebase_admin import credentials, firestore


class LocalSoftware:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'LocalSoftware_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&LocalSoftware')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('LocalSoftware', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/local_software/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Local Software'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&LocalSoftware'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_credential_file(self):
        filename, _filter = QFileDialog.getOpenFileName(
            self.dlg, "Select you Firebase Credential JSON file ","", '*.json')
        self.dlg.credential_path.setText(filename)

    def firebase_connect(self, credential):

        if not firebase_admin._apps:
            cred = credentials.Certificate(credential) 
            default_app = firebase_admin.initialize_app(cred)

        return firestore.client()

    def load_features(self, db):
        layer_name = self.dlg.layer_name_label.text()
        geojson_ref = db.collection('geojsons').document(layer_name)
        features_ref = geojson_ref.collection('features').stream()

        next_geom = next(features_ref).to_dict()
        geometry_type = next_geom['geometry']['type']
        layer = QgsVectorLayer(geometry_type, layer_name, "memory")
        pr = layer.dataProvider()

        # add fields
        fields = QgsJsonUtils.stringToFields(json.dumps(next_geom))
        pr.addAttributes(fields)
        layer.updateFields() # tell the vector layer to fetch changes from the provider

        # Enter editing mode
        layer.startEditing()
        for feature in features_ref:
            feature_dict = feature.to_dict()

            # Create QGIS feature from a geoJSON object
            qgis_feature = QgsJsonUtils.stringToFeatureList(json.dumps(feature_dict))[0]

            # Set the fields of the feature to the layer's fields
            qgis_feature.setFields(fields)
            # Set the properties of each feature by looping through all the keys of the JSON properties
            for key in feature_dict['properties']:
                #    print(key, feature_dict['properties'][key])
                qgis_feature.setAttribute(key, feature_dict['properties'][key])
                # QgsMessageLog.logMessage(key, 'local_software')
        
            # Add the features to the layer
            pr.addFeatures([qgis_feature])
            layer.commitChanges()

        # Show in project
        QgsProject.instance().addMapLayer(layer)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = LocalSoftwareDialog()
            self.dlg.push_button_path.clicked.connect(self.select_credential_file)




        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            db = self.firebase_connect(self.dlg.credential_path.text())
            self.load_features(db)
